### PR TITLE
Update waybar, move files in /usr/, changed style

### PR DESCRIPTION
**Pull request by Ly-sec**
Preview
Moved the waybar config files to `/usr/share/cachyos-hyprland-settings/waybar/` for easier management and access.
Enhanced the waybar style to provide a more polished and cohesive design.
Updated configuration paths to reflect the new structure and ensure smooth integration.

Also I moved the hyprland config files into `/usr/share/cachyos-hyprland-settings/hypr/` and edited the `hyprland.conf`to reflect the directory change.

### CODE REVIEW

**Comment by Shendisx** [comment]
> R-b, @Shendisx when you have the time, can you test this on your machine?

Sure i'll test it later

**Comment by Shendisx** [comment]
Two major issues:

1) Waybar no longer autostarts due to a bad path and the waybar.sh not executing
2) They're several path issues in:
- decorations.conf
- keybinds.conf
- variables.conf

**Comment by Ly-sec** [comment]
This should be fixed now, I hope.

**Comment by Shendisx** [comment]
> This should be fixed now, I hope.

Perfect, now both issues seem fixed.

**Comment by Shendisx** [comment]
Everything else seems fine and works so i'll merge.

**Pull request merged**
