### PR TITLE
Updated the links from 0.45.0 to 0.46.0

### PR DESCRIPTION
**Pull request by msmafra**
Updated the links from 0.45.0 to 0.46.0. Probably wasn't the best idea to have the URLs inside those files since it would/wil require to change it every single major release.
Removing all links may be the correct course here, instead of pointing to latest that contains what is being developed/non-release/git version.

### CODE REVIEW

**Comment by 1Naim** [comment]
Closing as specifying a version is unnecessary, e.g. https://wiki.hyprland.org/Configuring/Binds/. #21 already addresses this so this is obsolete.

**Comment by msmafra** [comment]
> Closing as specifying a version is unnecessary, e.g. https://wiki.hyprland.org/Configuring/Binds/#bind-flags. #21 already addresses this so this is obsolete.

I probably should clarify. URLs on the Hyprland wiki like this https://wiki.hyprland.org/Configuring/Binds/#bind-flags point to latest, and latest is not the current numbered release.
For example, assuming the time where 0.43.0 was the latest release, https://wiki.hyprland.org/0.43.0/Configuring/Binds/#bind-flags would have

```
l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
r -> release, will trigger on release of a key.
e -> repeat, will repeat when held.
n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
m -> mouse, see below
t -> transparent, cannot be shadowed by other binds.
i -> ignore mods, will ignore modifiers.

```

where latest,  https://wiki.hyprland.org/Configuring/Binds/#bind-flags, would have 

```
l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
r -> release, will trigger on release of a key.
e -> repeat, will repeat when held.
n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
m -> mouse, see below.
t -> transparent, cannot be shadowed by other binds.
i -> ignore mods, will ignore modifiers.
s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
d -> has description, will allow you to write a description for your bind.
p -> bypasses the app's requests to inhibit keybinds.
```

**Comment by 1Naim** [comment]
This is really a non-example. 0.43.0 is 3 months old already and holds no value in comparing latest vs point release comparisons. The other older versions except the latest point release also holds no value. If you can give an actual example of where the latest documentation doesn't match with the current latest point release, then we can consider using point release links.

**Comment by msmafra** [comment]
> This is really a non-example. 0.43.0 is 3 months old already and holds no value in comparing latest vs point release comparisons. The other older versions except the latest point release also holds no value. If you can give an actual example of where the latest documentation doesn't match with the current latest point release, then we can consider using point release links.

0.43.0 being 3 months old is completely irrelevant, as it is an example of the difference between the URLs containing the version number an the URL without it. The wiki URL without a version number points to what is being developed and may contain documentation not applicable to what the users have installed.

Just go to the page https://wiki.hyprland.org/version-selector/

image

**Pull request closed without merging**
